apiVersion: v1
kind: Service
metadata:
  name: weatheria-service
  namespace: default
  labels:
    app: weatheria
spec:
  type: LoadBalancer
  selector:
    app: weatheria
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
